##########################EKS#################
output "vpcs" {
  value = [
    data.aws_vpc.vpc.id,
    data.aws_subnet_ids.private
  ]
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "workers_asg_names" {
  value = module.eks.workers_asg_names

}

output "name-eks-openfinance" {
  value = module.eks.NAME-AUTOSCALING.*
}

#######################SCHEDULE####################

output "start-stop-node-dmz" {
  value = [
    module.start-stop-node-dmz.aws_autoscaling_schedule_start,
    module.start-stop-node-dmz.aws_autoscaling_schedule_stop
  ]
}

output "start-stop-node-app" {
  value = [
    module.start-stop-node-app.aws_autoscaling_schedule_start,
    module.start-stop-node-app.aws_autoscaling_schedule_stop
  ]
}
