{
 "title": "rpm-carro-2",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "TEMP MOTOR",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select tempMotor from exemplocarrodois;"
    }
   ]
  },
  {
   "title": "Nível correto do óleo",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select nivelOleo from exemplocarrodois;"
    }
   ]
  },
  {
   "title": "KM RODADO",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select kmRodado from exemplocarrodois;"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "select rpm from exemplocarrodois;"
    },
    {}
   ]
  }
 ]
}